# Generated by Django 3.1 on 2023-03-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userloginlogout',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='userloginlogout',
            name='total_time',
        ),
    ]
